[workspace]
resolver = "2"
members = ["crates/egui_alignments", "examples/alignments", "examples/containers"]

[workspace.package]
license = "MIT OR Apache-2.0"
version = "0.3.7"
edition = "2021"

[workspace.dependencies]
eframe = "0.34"
egui = "0.34"
egui_alignments = { path = "crates/egui_alignments" }
egui_extras = { version = "0.34", features = ["all_loaders"] }
egui_kittest = "0.34"
