[workspace]
resolver = "2"
members = ["crates/egui_alignments", "examples/alignments", "examples/containers"]

[workspace.package]
license = "MIT OR Apache-2.0"
version = "0.2.6"
edition = "2021"

[workspace.dependencies]
eframe = "0.31.1"
egui = "0.31.1"
egui_alignments = { path = "crates/egui_alignments" }
egui_extras = { version = "0.31.1", features = ["all_loaders"] }
