[package]
name = "containers"
license.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
eframe = "0.29.0"
egui = "0.29.0"
egui_alignments = { path = "../../crates/egui_alignments" }
egui_extras = { version = "0.29.0", features = ["all_loaders"] }
