[package]
name = "alignments"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.29.0"
egui = "0.29.0"
egui_alignments = { path = "../../crates/egui_alignments" }
egui_extras = { version = "0.29.0", features = ["all_loaders"] }
